In [25]:
import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Flatten, Embedding

In [26]:
reviews = ['nice food',
           'amazing restuarant',
           'too good',
           'just loved it',
           'will go again',
           'horrible food',
           'never go there',
           'poor service',
           'poor quality',
           'needs improvement']

sentiment = np.array([1,1,1,1,1,0,0,0,0,0])

In [28]:
vocab_size = 30
encoded_reviews = [one_hot(d, vocab_size) for d in reviews]
encoded_reviews

[[27, 1],
 [26, 29],
 [9, 12],
 [26, 14, 12],
 [17, 9, 21],
 [6, 1],
 [18, 9, 5],
 [19, 22],
 [19, 6],
 [5, 14]]

In [31]:
max_len = 3
padded_reviews = tf.keras.preprocessing.sequence.pad_sequences(encoded_reviews,
                                                               maxlen=max_len,
                                                               padding='post')
padded_reviews

array([[27,  1,  0],
       [26, 29,  0],
       [ 9, 12,  0],
       [26, 14, 12],
       [17,  9, 21],
       [ 6,  1,  0],
       [18,  9,  5],
       [19, 22,  0],
       [19,  6,  0],
       [ 5, 14,  0]], dtype=int32)

In [37]:
X = padded_reviews
y = sentiment

In [35]:
Embedding_vector_size = 5

model = tf.keras.Sequential([
  tf.keras.layers.Embedding(vocab_size, 
                            Embedding_vector_size, 
                            input_length=max_len,
                            name='embedding'),
  tf.keras.layers.Flatten(),
  tf.keras.layers.Dense(1, activation='sigmoid')
])

In [36]:
model.compile(loss='binary_crossentropy',
              optimizer='adam',
              metrics='accuracy')

In [38]:
model.fit(X, y, epochs=50)

Epoch 1/50
1/1 [==============================] - 1s 764ms/step - loss: 0.6975 - accuracy: 0.5000
Epoch 2/50
1/1 [==============================] - 0s 6ms/step - loss: 0.6961 - accuracy: 0.5000
Epoch 3/50
1/1 [==============================] - 0s 5ms/step - loss: 0.6947 - accuracy: 0.5000
Epoch 4/50
1/1 [==============================] - 0s 7ms/step - loss: 0.6932 - accuracy: 0.5000
Epoch 5/50
1/1 [==============================] - 0s 5ms/step - loss: 0.6918 - accuracy: 0.5000
Epoch 6/50
1/1 [==============================] - 0s 5ms/step - loss: 0.6904 - accuracy: 0.5000
Epoch 7/50
1/1 [==============================] - 0s 4ms/step - loss: 0.6890 - accuracy: 0.6000
Epoch 8/50
1/1 [==============================] - 0s 4ms/step - loss: 0.6876 - accuracy: 0.7000
Epoch 9/50
1/1 [==============================] - 0s 4ms/step - loss: 0.6862 - accuracy: 0.7000
Epoch 10/50
1/1 [==============================] - 0s 6ms/step - loss: 0.6848 - accuracy: 0.7000
Epoch 11/50
1/1 [====================

In [55]:
weights = model.get_layer('embedding').get_weights()[0]

In [56]:
len(weights)

30

In [52]:
weights[11]

array([ 0.02720623, -0.04304815, -0.0009367 ,  0.04512915, -0.00708035],
      dtype=float32)

In [51]:
weights[3]

array([-0.01989353,  0.04995536,  0.04987884,  0.02978365, -0.02253315],
      dtype=float32)